# Generated by Django 3.2.5 on 2021-07-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdnotes', '0002_auto_20210710_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=250)),
                ('polish_name', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ('polish_name',),
            },
        ),
    ]
