# Generated by Django 3.2.5 on 2021-07-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdnotes', '0003_birdspecies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='id',
        ),
        migrations.AlterField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key='polish_name', serialize=False, to='birdnotes.birdspecies', verbose_name='Species'),
        ),
    ]
