# Generated by Django 3.2.5 on 2021-07-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdnotes', '0004_auto_20210723_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdnotes.birdspecies'),
        ),
    ]
