# Generated by Django 3.2.5 on 2021-07-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdnotes', '0006_auto_20210723_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='behaviour',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='gender',
            field=models.CharField(choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female')], default='unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='observation',
            name='weather',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
