# Generated by Django 3.2.5 on 2021-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdnotes', '0007_auto_20210724_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
